version: '3.8'
services:
  # API
  cuba-api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    image: cuba-api
    container_name: cuba-api
    working_dir: /var/www
    restart: on-failure
    ports:
      - '4500:4500'
    volumes:
      - .:/var/www
    depends_on:
      - mongo
      - mongo-test
    networks:
      - cuba-back

  mongo:
    image: mongo:latest
    container_name: cuba-mongo
    ports:
      - 27017:27017
    volumes:
      - './mongo/:/data/db'
    networks:
      - cuba-back
    environment:
      MONGO_INITDB_ROOT_USERNAME: cuba
      MONGO_INITDB_ROOT_PASSWORD: OzVPKo
      MONGO_INITDB_DATABASE: cuba

  mongo-test:
    image: mongo:latest
    container_name: cuba-mongo-test
    ports:
      - 27018:27017
    volumes:
      - './mongo/test:/data/db'
    networks:
      - cuba-back
    environment:
      MONGO_INITDB_ROOT_USERNAME: cuba-test
      MONGO_INITDB_ROOT_PASSWORD: OzVPKo
      MONGO_INITDB_DATABASE: cuba

networks:
  cuba-back:
    driver: bridge
