version: '3.8'
services:
  # API
  cuba-api:
    build:
      context: .
      dockerfile: ./docker/api.dockerfile
    image: cuba-api
    container_name: cuba-api
    working_dir: /var/www
    restart: on-failure
    ports:
      - '4500:4500'
    volumes:
      - .:/var/www
    depends_on:
      - mongo-rs
    networks:
      - cuba-back

  # Mongo ReplicaSet
  mongo-rs:
    build:
      context: .
      dockerfile: ./docker/mongo-rs.dockerfile
      args:
        MONGO_VERSION: 7
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      MONGO_COMMAND: 'mongosh'
    command: --replSet rs0 --keyFile /data/db/mongo-keyfile --bind_ip_all --port 27018
    ports:
      - '27018:27018'
    restart: unless-stopped
    healthcheck:
      test:
        [
          'CMD',
          'mongosh',
          'admin',
          '--port',
          '27018',
          '--eval',
          "db.adminCommand('ping').ok",
        ]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
    networks:
      - cuba-back

networks:
  cuba-back:
    driver: bridge
