version: "3.8"
services:
  # API
  # study-api:
  #   build:
  #     context: .
  #     dockerfile: ./docker/api.dockerfile
  #   image: study-api
  #   container_name: study-api
  #   working_dir: /var/www
  #   restart: on-failure
  #   ports: 
  #     "3000:3000"
  #   volumes: .:/var/www
  #   depends_on: mongo-rs
  #   networks: study-network

  # Mongo ReplicaSet
  mongo-rs:
    build:
      context: .
      dockerfile: ./docker/mongo-rs.dockerfile
      args:
        MONGO_VERSION: 7
    environment:
      MONGO_REPLICA_HOST: 127.0.0.1
      MONGO_REPLICA_PORT: 27018
      MONGO_COMMAND: "mongosh"
    ports: "27018:27018"
    restart: unless-stopped
  healthcheck: 
    test:
      [
        "CMD",
        "mongosh",
        "admin",
        "--port",
        "27018",
        "--eval",
        "db.adminCommand('ping').ok",
      ]
    interval: 1m30s
    timeout: 30s
    retries: 5
    start_period: 30
  networks: 
    - study-network

networks:
  study-network:
    driver: bridge